
logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
    cn.com.taiji.security.securityday1: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityclass?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    session:
      cookie:
        name: SECURITYCLASS