#spring:
#  security:
#    user:
#      name: user
#      password: 1

logging:
  level:
    root: INFO
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.springframework.boot.autoconfugure: info
    cn.com.taiji.security.securityday1: DEBUG

#≈‰÷√ ˝æ›‘¥
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityclass?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
